add_bc_loss: 0
batch_size: 256
bc_policy: ''
discount: 0.99
end_on_success: 1
env_reward_scale: 1
episode_length: 300
freeze_bc_replay: 1
image_size: 224
load_policy_only: 0
load_pretrained_agent: release/model/robomimic/square_cql_less/model0.pt
load_ref_agent: ''
log_per_step: 5
mix_rl_rate: 1
mp_eval: 0
nstep: 3
num_critic_update: 5
num_eval_episode: 10
num_train_step: 300000
num_warm_up_episode: 100
obs_stack: 1
preload_datapath: release/data/robomimic/square/processed_data96.hdf5
preload_num_data: 100
pretrain_epoch_len: 10000
pretrain_num_epoch: 20
pretrain_only: 1
prop_stack: 1
q_agent:
  act_method: cql
  actor:
    dropout: 0
    feature_dim: 128
    hidden_dim: 1024
    max_action_norm: -1
    orth: 1
    spatial_emb: 0
  awac_beta: 1.0
  bc_loss_coef: 0.1
  bc_loss_dynamic: 0
  bootstrap_method: cql
  cql_weight: 1.0
  critic:
    drop: 0
    feature_dim: 128
    fuse_patch: 1
    hidden_dim: 1024
    norm_weight: 0
    orth: 1
    spatial_emb: 0
  critic_target_tau: 0.01
  device: cuda
  enc_type: vit
  entropy_weight: 1.0
  ibrl_eps_greedy: 1
  lr: 0.0001
  min_q_weight: 1.0
  num_random_actions: 4
  resnet:
    downsample: default
    norm_layer: gnn
    shallow: 0
    stem: default
  resnet96:
    shallow: 0
    use_1x1: 0
  soft_ibrl_beta: 10
  state_actor:
    dropout: 0.5
    hidden_dim: 1024
    layer_norm: 0
    num_layer: 3
    orth: 0
  state_critic:
    append_action: 0
    dropout: 0.0
    hidden_dim: 1024
    layer_norm: 1
    num_k: 2
    num_layer: 3
    num_q: 5
    orth: 0
  stddev_clip: 0.3
  target_q_gap: 5.0
  use_prop: 0
  vit:
    depth: 3
    embed_dim: 128
    embed_norm: 0
    embed_style: embed1
    num_heads: 4
    patch_size: 8
    stride: -1
record_dir: null
replay_buffer_size: 1000
rl_camera: agentview+robot0_eye_in_hand
rl_image_size: 96
save_dir: exp/compare/square_cql_test
save_per_success: -1
seed: 1
state_stack: 3
stddev_max: 0.1
stddev_min: 0.1
stddev_step: 500000
task_name: NutAssemblySquare
update_freq: 2
use_state: 1
use_wb: 0
